-- ================================================
-- AGREGAR PRODUCTOS FALTANTES
-- Sakura Coffee - PostgreSQL
-- Este script agrega los 54 productos que faltan
-- ================================================

-- Primero, agregar las categorías faltantes
INSERT INTO categorias (id, nombre) VALUES
    (3, 'Desayunos'),
    (4, 'Postres'),
    (5, 'Sándwiches'),
    (6, 'Snacks'),
    (7, 'Bowls'),
    (8, 'Café Especialidad'),
    (9, 'Bebidas'),
    (10, 'Jugos Naturales'),
    (11, 'Crepés y Waffles'),
    (12, 'Extras')
ON CONFLICT (id) DO UPDATE SET nombre = EXCLUDED.nombre;

-- Agregar productos faltantes (IDs 25-78)
INSERT INTO productos (id, nombre, descripcion, precio, categoria_id, stock, destacado, activo, tipo) VALUES
    (25, 'Vegan Nut & Banana Toast', 'Pan tostado con crema de maní, banano y miel de chía', 3.99, 3, 20, false, true, NULL),
    (26, 'American Breakfast', 'Waffles con maple, tocino y huevos revueltos', 5.99, 3, 15, false, true, NULL),
    (27, 'Classic Breakfast', 'Tostadas con huevos revueltos, fruta y mermelada', 4.75, 3, 25, false, true, NULL),
    (28, 'Morning Boost', 'Elige entre bowl de avena, smoothie o açaí con pan tostado', 4.99, 3, 20, false, true, NULL),
    (29, 'Sweet Morning Stacks', 'Pancakes con fruta fresca, mermelada y miel de maple', 5.99, 3, 18, false, true, NULL),
    (30, 'Sweet Morning Stacks (Vegan)', 'Pancakes veganos con fruta fresca y mermelada', 6.99, 3, 15, false, true, NULL),
    (31, 'Sweet Breakfast', 'Tostadas francesas con frutas y frutos secos', 6.50, 3, 12, false, true, NULL),
    (32, 'Sándwich de Pollo', 'Pollo con salsa de champiñones y queso fundido', 3.50, 5, 35, false, true, NULL),
    (33, 'Sándwich de Queso', 'Tres tipos de quesos fundidos en pan tostado', 2.99, 5, 40, false, true, NULL),
    (34, 'Sándwich de la Casa', 'Huevo, tocino y queso derretido', 3.50, 5, 30, false, true, NULL),
    (35, 'Sándwich Pesto', 'Pesto, aguacate, tomate y queso derretido', 3.00, 5, 25, false, true, NULL),
    (36, 'Katsu Sando', 'Filete de cerdo empanizado con salsa tonkatsu', 3.50, 5, 20, false, true, NULL),
    (37, 'Tamago Sando', 'Ensalada de huevo con mayonesa japonesa', 3.00, 5, 30, false, true, NULL),
    (38, 'Teriyaki Chicken Sando', 'Pollo glaseado en salsa teriyaki', 3.50, 5, 25, false, true, NULL),
    (1, 'Nachos con Queso', 'Crujientes nachos con queso cheddar derretido', 2.50, 6, 45, false, true, NULL),
    (2, 'Nachos Mixtos', 'Nachos con queso cheddar y toppings especiales', 3.00, 6, 40, false, true, NULL),
    (3, 'Papas Fritas', 'Papas fritas con queso cheddar y tocino', 2.50, 6, 50, false, true, NULL),
    (4, 'Extra Papas Fritas', 'Porción adicional de papas fritas', 1.25, 6, 60, false, true, NULL),
    (5, 'Brownie con Helado y Crema', 'Brownie caliente con helado y crema batida', 3.99, 4, 40, false, true, NULL),
    (6, 'Pan de Banano', 'Esponjoso pan de banano con toque de vainilla', 1.99, 4, 50, false, true, NULL),
    (7, 'Blondie de Café', 'Blondie con toque de café y chocolate blanco', 1.99, 4, 45, false, true, NULL),
    (8, 'Cheesecake de la Casa', 'Cheesecake cremoso con base crujiente', 3.75, 4, 30, false, true, NULL),
    (9, 'Pie de Manzana', 'Manzanas con canela en masa dorada y crujiente', 2.99, 4, 35, false, true, NULL),
    (10, 'Tiramisú', 'Capas de bizcocho con café, mascarpone y cacao', 3.00, 4, 25, false, true, NULL),
    (11, 'Chocolate Caliente', 'Delicioso chocolate derretido con leche espumosa', 2.99, 1, 50, false, true, NULL),
    (12, 'Chai Latte', 'Mezcla perfecta de té y especias con leche cremosa', 2.50, 1, 60, false, true, NULL),
    (13, 'Matcha Latte', 'Matcha vibrante con leche suave, energizante', 2.50, 1, 70, false, true, NULL),
    (14, 'Té de Hierbas Relajante', 'Relajante infusión de hierbas naturales', 2.00, 1, 80, false, true, NULL),
    (15, 'Espresso Sakura', 'Café concentrado con esencia de cerezo y notas florales', 3.50, 1, 40, false, true, NULL),
    (16, 'Matcha Latte Tradicional', 'Matcha ceremonial batido con leche vaporizada y miel', 3.75, 1, 45, false, true, NULL),
    (17, 'Hojicha Latte', 'Té verde tostado con leche cremosa y notas caramelizadas', 3.75, 1, 35, false, true, NULL),
    (18, 'Genmaicha', 'Té verde con arroz tostado, estilo tradicional japonés', 3.50, 1, 50, false, true, NULL),
    (19, 'Té Frío', 'Refrescante y ligero, ideal para cualquier momento', 2.50, 2, 60, false, true, 'sin-cafe'),
    (20, 'Sakura Té Frío', 'Té helado con un toque floral, perfecto para una pausa', 2.99, 2, 50, false, true, 'sin-cafe'),
    (21, 'Chai Latte Frío', 'Especias y té negro en versión fría, cremosa', 2.75, 2, 55, false, true, 'sin-cafe'),
    (22, 'Matcha Latte Frío', 'Matcha vibrante batido con leche fría, refrescante', 2.75, 2, 65, false, true, 'sin-cafe'),
    (23, 'Omelette', 'Omelette esponjoso con ingredientes frescos, pan tostado y tomate confitado', 4.50, 3, 30, false, true, NULL),
    (24, 'Avocado Toast', 'Tostada con aguacate, queso feta, remolacha y semillas de chía', 3.99, 3, 25, false, true, NULL),
    (39, 'Açaí Bowl', 'Pulpa de açaí con frutas frescas y toppings', 4.50, 7, 20, false, true, NULL),
    (40, 'Bowl de Avena', 'Avena cremosa con fruta, almendras y miel', 3.50, 7, 25, false, true, NULL),
    (41, 'Smoothie Bowl', 'Mezcla de frutos rojos con toppings saludables', 3.75, 7, 18, false, true, NULL),
    (42, 'Espresso', 'Café puro, intenso y robusto', 1.25, 8, 100, false, true, NULL),
    (43, 'Doppio', 'Doble shot de espresso para café fuerte', 1.50, 8, 90, false, true, NULL),
    (44, 'Americano', 'Café suave y ligero, perfecto para disfrutar', 1.75, 8, 95, false, true, NULL),
    (45, 'Macchiato', 'Espresso con toque de espuma de leche', 1.99, 8, 85, false, true, NULL),
    (46, 'Flat White', 'Doble espresso con leche al vapor, suave', 2.75, 8, 70, false, true, NULL),
    (47, 'Cappuccino', 'Espresso, leche y espuma espesa clásica', 2.35, 8, 80, false, true, NULL),
    (48, 'Mocaccino', 'Mezcla de café y chocolate con leche', 2.50, 8, 75, false, true, NULL),
    (49, 'Signature Cappuccino', 'Cappuccino especial con sabor a elegir', 2.50, 8, 65, false, true, NULL),
    (50, 'Agua con gas', 'Agua mineral con gas', 1.25, 9, 200, false, true, NULL),
    (51, 'Agua sin gas', 'Agua mineral sin gas', 1.00, 9, 250, false, true, NULL),
    (52, 'Coca-Cola', 'Refresco de cola', 0.90, 9, 150, false, true, NULL),
    (53, 'Sprite', 'Refresco de lima-limón', 0.90, 9, 140, false, true, NULL),
    (54, 'Fanta', 'Refresco de naranja', 0.90, 9, 130, false, true, NULL),
    (55, 'Fioravanti', 'Refresco de frutas', 0.90, 9, 120, false, true, NULL),
    (56, 'Jugo de Naranja', 'Jugo natural de naranja', 1.99, 10, 80, false, true, NULL),
    (57, 'Jugo de Frutilla', 'Jugo natural de frutilla', 1.99, 10, 70, false, true, NULL),
    (58, 'Jugo de Mora', 'Jugo natural de mora', 1.99, 10, 60, false, true, NULL),
    (59, 'Limonada Imperial', 'Limonada refrescante tradicional', 1.99, 10, 90, false, true, NULL),
    (60, 'Limonada Rosada', 'Limonada con toque especial rosado', 2.50, 10, 50, false, true, NULL),
    (61, 'Crepé Arequipe y Queso', 'Arequipe cremoso y queso suave en crepé', 3.99, 11, 25, false, true, NULL),
    (62, 'Crispy Kiss Crepe', 'Crepé con dulce de leche y frutas frescas', 4.50, 11, 20, false, true, NULL),
    (63, 'Waffle de Mantequilla y Miel', 'Waffle dorado con mantequilla y miel', 3.99, 11, 30, false, true, NULL),
    (64, 'Waffle de Frutos del Bosque', 'Waffle con mezcla de frutos del bosque', 3.99, 11, 22, false, true, NULL),
    (65, 'Waffle de Nutella y Banano', 'Waffle con Nutella, banano y helado', 5.99, 11, 18, false, true, NULL),
    (66, 'Waffle de Arequipe con Helado', 'Waffle con arequipe cremoso y helado', 5.99, 11, 15, false, true, NULL),
    (67, 'Crepé Veggie', 'Crepé con frutas frescas y mermelada', 4.50, 11, 20, false, true, NULL),
    (68, 'Veggie Waffle', 'Waffle con frutas frescas y mermelada', 4.50, 11, 18, false, true, NULL),
    (69, 'Crema', 'Porción adicional de crema', 0.50, 12, 200, false, true, NULL),
    (70, 'Leche de Almendras', 'Leche vegetal de almendras', 0.85, 12, 150, false, true, NULL),
    (71, 'Caramelo', 'Jarabe o topping de caramelo', 0.50, 12, 180, false, true, NULL),
    (72, 'Queso', 'Porción adicional de queso', 0.75, 12, 170, false, true, NULL),
    (73, 'Huevo', 'Huevo adicional', 0.75, 12, 160, false, true, NULL),
    (74, 'Chocolate', 'Topping o jarabe de chocolate', 0.50, 12, 190, false, true, NULL),
    (75, 'Helado', 'Bola de helado adicional', 1.00, 12, 120, false, true, NULL),
    (76, 'Jarabe', 'Jarabe de sabor a elección', 0.50, 12, 210, false, true, NULL),
    (77, 'Tocino', 'Porción adicional de tocino', 1.60, 12, 100, false, true, NULL),
    (78, 'Fruta Picada', 'Porción de fruta fresca picada', 1.45, 12, 90, false, true, NULL)
ON CONFLICT (id) DO UPDATE SET 
    nombre = EXCLUDED.nombre,
    descripcion = EXCLUDED.descripcion,
    precio = EXCLUDED.precio,
    categoria_id = EXCLUDED.categoria_id,
    stock = EXCLUDED.stock,
    destacado = EXCLUDED.destacado,
    activo = EXCLUDED.activo,
    tipo = EXCLUDED.tipo;

-- Verificación
SELECT 'Productos totales:' as info, COUNT(*) as total FROM productos;
SELECT 'Categorías totales:' as info, COUNT(*) as total FROM categorias;
